apiVersion: apps/v1
kind: Deployment
metadata:
  name: div4u-backend
  labels:
    app: div4u-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: div4u-backend
  template:
    metadata:
      labels:
        app: div4u-backend
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: backend
        image: harbor.bluesunnywings.com/div4u/div4u-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: PORT
          value: "3001"
        - name: SEOUL_API_KEY
          valueFrom:
            secretKeyRef:
              name: seoul-api-secret
              key: seoul-api-key
        - name: SEOUL_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SEOUL_API_BASE_URL
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CORS_ORIGIN
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"