apiVersion: apps/v1
kind: Deployment
metadata:
  name: div4u-frontend
  namespace: div4u
  labels:
    app: div4u-frontend
    environment: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: div4u-frontend
  template:
    metadata:
      labels:
        app: div4u-frontend
        environment: production
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: frontend
        image: harbor.bluesunnywings.com/div4u/div4u-frontend:ee3b847741073e52f1f2961f431be2d13d3d72ee
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: PORT
          value: "3000"
        - name: BACKEND_SERVICE_URL
          value: "http://div4u-backend-service:3001"
        - name: COMPARISON_SERVICE_URL
          value: "http://div4u-comparison-service:3002"
        # Build-time 환경변수들 (Docker 빌드 시 사용)
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VITE_API_BASE_URL
        - name: VITE_COMPARISON_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VITE_COMPARISON_API_URL
        - name: VITE_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VITE_APP_NAME
        - name: VITE_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VITE_APP_VERSION
        # BFF 방식에서는 nginx-config 불필요
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      # BFF 방식에서는 nginx-config volume 불필요
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001