apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- namespace.yaml
- ingress.yaml
# - harbor-secret.yaml  # 수동으로 생성 필요
# - seoul-api-secret.yaml  # 수동으로 생성 필요

