apiVersion: apps/v1
kind: Deployment
metadata:
  name: div4u-comparison
  labels:
    app: div4u-comparison
spec:
  replicas: 1
  selector:
    matchLabels:
      app: div4u-comparison
  template:
    metadata:
      labels:
        app: div4u-comparison
    spec:
      containers:
      - name: comparison
        image: harbor.bluesunnywings.com/div4u/div4u-comparison:latest
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"