apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: div4u
data:
  # Common
  NODE_ENV: "production"
  
  # Backend
  PORT: "3001"
  CORS_ORIGIN: "https://www.div4u.com"
  SEOUL_API_BASE_URL: "http://openapi.seoul.go.kr:8088"
  
  # Frontend - Ingress를 통한 API 호출
  VITE_API_BASE_URL: "/api"
  VITE_COMPARISON_API_URL: "/api/comparison"
  VITE_APP_NAME: "div4u"
  VITE_APP_VERSION: "1.0.0"
  
  # Comparison - Kubernetes Service DNS 사용
  COMPARISON_PORT: "3002"
  # 같은 네임스페이스 내 서비스 통신 (Kubernetes DNS)
  BACKEND_SERVICE_NAME: "div4u-backend-service"
  BACKEND_SERVICE_PORT: "3001"
  # 또는 직접 URL (Kubernetes DNS 방식)
  CORE_API_URL: "http://div4u-backend-service:3001/api"
  CACHE_TTL_MINUTES: "5"
  ALLOWED_ORIGINS: "https://www.div4u.com"
  LOG_LEVEL: "warn"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: div4u
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        # 로그 설정
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        
        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;
        
        # Gzip 압축
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json;
        
        server {
            listen 80;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;
            
            # 보안 헤더
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Referrer-Policy "strict-origin-when-cross-origin" always;
            
            
            # SPA 라우팅 지원
            location / {
                try_files $uri $uri/ /index.html;
            }
            
            # 정적 파일 캐싱
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
            
            # 헬스체크
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    }