apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: div4u-frontend-application
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://github.com/CCCR-div4u/div4u2.git'
    targetRevision: HEAD
    path: k8s/frontend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: div4u
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m