apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: div4u-production
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://github.com/CCCR-div4u/div4u.git'
    targetRevision: main
    path: k8s/environments/production
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: div4u-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # 더 빠른 감지를 위한 설정
  revisionHistoryLimit: 10