apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: div4u-staging

resources:
- ../../base/backend
- ../../base/frontend
- ../../base/comparison
- ../../base/common

patches:
- path: patches/configmap-staging.yaml
  target:
    kind: ConfigMap
    name: app-config
- path: patches/ingress-staging.yaml
  target:
    kind: Ingress
    name: div4u-ingress
- path: patches/imagepullsecrets-staging.yaml

images:
- name: harbor.bluesunnywings.com/div4u/div4u-backend
  newName: harbor.bluesunnywings.com/div4u-staging/div4u-backend
  newTag: 51212e4ead26906b2f6381ed93ed56d3daf1c4fb
- name: harbor.bluesunnywings.com/div4u/div4u-frontend
  newName: harbor.bluesunnywings.com/div4u-staging/div4u-frontend
  newTag: 51212e4ead26906b2f6381ed93ed56d3daf1c4fb
- name: harbor.bluesunnywings.com/div4u/div4u-comparison
  newName: harbor.bluesunnywings.com/div4u-staging/div4u-comparison
  newTag: 51212e4ead26906b2f6381ed93ed56d3daf1c4fb

labels:
- pairs:
    environment: staging

namePrefix: staging-