apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: div4u-staging

resources:
- ../../base/backend
- ../../base/frontend
- ../../base/comparison
- ../../base/common

patches:
- path: patches/configmap-staging.yaml
  target:
    kind: ConfigMap
    name: app-config
- path: patches/ingress-staging.yaml
  target:
    kind: Ingress
    name: div4u-ingress
    
- path: patches/frontend-service-urls.yaml
  target:
    kind: Deployment
    name: div4u-frontend

images:
- name: harbor.bluesunnywings.com/div4u/div4u-backend
  newName: harbor.bluesunnywings.com/div4u-staging/div4u-backend
  newTag: abae861919bcc1fbffaccad09abaea370e103b59
- name: harbor.bluesunnywings.com/div4u/div4u-frontend
  newName: harbor.bluesunnywings.com/div4u-staging/div4u-frontend
  newTag: abae861919bcc1fbffaccad09abaea370e103b59
- name: harbor.bluesunnywings.com/div4u/div4u-comparison
  newName: harbor.bluesunnywings.com/div4u-staging/div4u-comparison
  newTag: abae861919bcc1fbffaccad09abaea370e103b59

labels:
- pairs:
    environment: staging
    
namePrefix: staging-